# Generated by Django 4.2.30 on 2026-09-02 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0003_intervenant_etudiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=200)),
                ('debut', models.DateTimeField()),
                ('fin', models.DateTimeField()),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='planning.classe')),
                ('intervenant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='planning.intervenant')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cours', to='planning.salle')),
            ],
            options={
                'ordering': ['debut'],
            },
        ),
    ]
